name: "Champ AI Code Review"
description: "Uses Gemini AI (with OpenRouter fallback) to review PRs."
author: "Tushar Nikam"
branding:
  icon: "check-circle"
  color: "blue"
inputs:
  github_token:
    description: "GitHub Token to access PR details"
    required: true
  google_api_key:
    description: "Google Gemini API Key"
    required: true
  openrouter_api_key:
    description: "OpenRouter API Key (fallback)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GOOGLE_API_KEY: ${{ inputs.google_api_key }}
    OPENROUTER_API_KEY: ${{ inputs.openrouter_api_key }}
